<a href="https://colab.research.google.com/github/alishadaudi/ddsa-anomaly-detection-and-clustering-zillow-project/blob/main/Anomaly_Detection_%26_Clustering_Zillow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Code snippet 1
# Installing pycaret for ML modeling
!pip install git+https://github.com/pycaret/pycaret.git

In [ ]:
# Code snippet 2
# Importing Anomaly detection ML modules from pycaret
from pycaret.anomaly import *

In [ ]:
# Code snippet 3
# Importing the zillow/real estate dataset
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/nvamsimohan/DallasDSA/refs/heads/main/Zillow%20Tarrant%20County%20Raw%20Data.csv')

data

,beds,baths,sqft,Age,lot_size,property_type,exterior_walls,roof,basement,restaurants,...,beauty_spas,active_life,median_age,married,college_grad,property_tax,insurance,median_school,num_schools,Sales_price
0,1,1,584,9,0,Apartment / Condo / Townhouse,Wood Siding,NaN,0,107,...,47,58,33,65,84,234,81,9.0,3,295850
1,1,1,612,57,0,Apartment / Condo / Townhouse,Brick,Composition Shingle,1,105,...,26,14,39,73,69,169,51,3.0,3,216500
2,1,1,615,59,0,Apartment / Condo / Townhouse,Wood Siding,NaN,0,183,...,74,62,28,15,86,216,74,8.0,3,279900
3,1,1,618,22,33541,Apartment / Condo / Townhouse,Wood Siding,NaN,0,198,...,72,83,36,25,91,265,92,9.0,3,379900
4,1,1,634,30,0,Apartment / Condo / Townhouse,Brick,NaN,0,149,...,50,73,37,20,75,88,30,9.0,3,340000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1878,5,6,6381,18,224334,Single-Family,Stucco,Composition Shingle,1,0,...,0,1,46,76,87,1250,381,10.0,3,385000
1879,5,6,6501,66,23086,Single-Family,Brick,Composition Shingle,1,45,...,61,11,42,73,61,1553,473,9.0,3,690000
1880,5,6,7064,27,217800,Single-Family,Metal,Composition Shingle,1,5,...,1,2,43,87,66,942,287,8.0,1,600000
1881,5,6,7500,16,8886,Single-Family,Siding (Alum/Vinyl),Asphalt,1,18,...,8,6,43,61,51,803,245,5.0,2,759900
1882,5,6,7515,64,10497,Single-Family,Brick,Composition Shingle,1,0,...,0,5,37,80,86,1459,444,9.0,3,735000

In [ ]:
# Code snippet 4
# Display the data columns
data.columns

Index(['beds', 'baths', 'sqft', 'Age', 'lot_size', 'property_type',
       'exterior_walls', 'roof', 'basement', 'restaurants', 'groceries',
       'nightlife', 'cafes', 'shopping', 'arts_entertainment', 'beauty_spas',
       'active_life', 'median_age', 'married', 'college_grad', 'property_tax',
       'insurance', 'median_school', 'num_schools', 'Sales_price'],
      dtype='object')

In [ ]:
# Code snippet 5
# Configuring/setting up the anomaly detection algos
anomaly_setup = setup(data)

In [ ]:
# Code snippet 6
# Building an anomaly detection model using KNN algorithm
knn_model = create_model('knn')

Processing:   0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
# Code snippet 7
# Identifying/predicting the anomalies using the knn model
knn_anomalies = predict_model(knn_model, data)

# Displaying KNN anomalies
knn_anomalies

,beds,baths,sqft,Age,lot_size,property_type,exterior_walls_Wood Siding,exterior_walls_Brick,exterior_walls_Concrete Block,exterior_walls_Wood,...,median_age,married,college_grad,property_tax,insurance,median_school,num_schools,Sales_price,Anomaly,Anomaly_Score
0,1.0,1.0,584.0,9.0,0.0,0.0,1.0,0.0,0.0,0.0,...,33.0,65.0,84.0,234.0,81.0,9.0,3.0,295850.0,0,1058.478625
1,1.0,1.0,612.0,57.0,0.0,0.0,0.0,1.0,0.0,0.0,...,39.0,73.0,69.0,169.0,51.0,3.0,3.0,216500.0,0,1542.812043
2,1.0,1.0,615.0,59.0,0.0,0.0,1.0,0.0,0.0,0.0,...,28.0,15.0,86.0,216.0,74.0,8.0,3.0,279900.0,0,536.152963
3,1.0,1.0,618.0,22.0,33541.0,0.0,1.0,0.0,0.0,0.0,...,36.0,25.0,91.0,265.0,92.0,9.0,3.0,379900.0,0,8684.916637
4,1.0,1.0,634.0,30.0,0.0,0.0,0.0,1.0,0.0,0.0,...,37.0,20.0,75.0,88.0,30.0,9.0,3.0,340000.0,0,1583.929607
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1878,5.0,6.0,6381.0,18.0,224334.0,1.0,0.0,0.0,0.0,0.0,...,46.0,76.0,87.0,1250.0,381.0,10.0,3.0,385000.0,1,83879.408345
1879,5.0,6.0,6501.0,66.0,23086.0,1.0,0.0,1.0,0.0,0.0,...,42.0,73.0,61.0,1553.0,473.0,9.0,3.0,690000.0,0,10610.535001
1880,5.0,6.0,7064.0,27.0,217800.0,1.0,0.0,0.0,0.0,0.0,...,43.0,87.0,66.0,942.0,287.0,8.0,1.0,600000.0,1,90006.028843
1881,5.0,6.0,7500.0,16.0,8886.0,1.0,0.0,0.0,0.0,0.0,...,43.0,61.0,51.0,803.0,245.0,5.0,2.0,759900.0,0,7099.341519
1882,5.0,6.0,7515.0,64.0,10497.0,1.0,0.0,1.0,0.0,0.0,...,37.0,80.0,86.0,1459.0,444.0,9.0,3.0,735000.0,0,7063.793103

In [ ]:
# Code snippet 8
# Displaying ONLY the anomalies
knn_anomalies[knn_anomalies['Anomaly'] == 1]

,beds,baths,sqft,Age,lot_size,property_type,exterior_walls_Wood Siding,exterior_walls_Brick,exterior_walls_Concrete Block,exterior_walls_Wood,...,median_age,married,college_grad,property_tax,insurance,median_school,num_schools,Sales_price,Anomaly,Anomaly_Score
26,1.0,1.0,709.0,17.0,111513.0,0.0,1.0,0.0,0.0,0.0,...,33.0,40.0,96.0,316.0,109.0,5.0,3.0,377000.0,1,26303.145401
44,1.0,1.0,771.0,17.0,111513.0,0.0,1.0,0.0,0.0,0.0,...,33.0,40.0,96.0,345.0,119.0,5.0,3.0,397400.0,1,37231.988051
87,1.0,2.0,814.0,14.0,96703.0,0.0,1.0,0.0,0.0,0.0,...,45.0,60.0,71.0,321.0,93.0,9.0,3.0,299700.0,1,47273.468193
102,2.0,1.0,875.0,72.0,1220551.0,0.0,0.0,1.0,0.0,0.0,...,33.0,35.0,87.0,230.0,79.0,6.0,3.0,292999.0,1,880904.033810
172,2.0,2.0,915.0,17.0,183387.0,0.0,0.0,1.0,0.0,0.0,...,30.0,46.0,41.0,265.0,92.0,7.0,3.0,385000.0,1,43479.963699
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1875,5.0,5.0,7594.0,16.0,36154.0,1.0,0.0,1.0,0.0,0.0,...,52.0,85.0,57.0,1061.0,323.0,5.5,2.0,235000.0,1,18885.302069
1876,5.0,5.0,7842.0,19.0,436035.0,1.0,0.0,0.0,0.0,0.0,...,48.0,76.0,62.0,881.0,249.0,7.5,2.0,760000.0,1,103704.689948
1877,5.0,5.0,8450.0,18.0,91911.0,1.0,0.0,0.0,0.0,0.0,...,35.0,91.0,85.0,1966.0,599.0,10.0,3.0,555000.0,1,35478.855464
1878,5.0,6.0,6381.0,18.0,224334.0,1.0,0.0,0.0,0.0,0.0,...,46.0,76.0,87.0,1250.0,381.0,10.0,3.0,385000.0,1,83879.408345
1880,5.0,6.0,7064.0,27.0,217800.0,1.0,0.0,0.0,0.0,0.0,...,43.0,87.0,66.0,942.0,287.0,8.0,1.0,600000.0,1,90006.028843

In [ ]:
# Code snippet 9
# Exporting all anomalies data to a CSV file
knn_anomalies.to_csv('knn_anomalies.csv')

In [ ]:
# Code snippet 10
# Importing Clustering ML modules from pycaret
from pycaret.clustering import *

In [ ]:
# Code snippet 11
# Configuring/setting up the clustering algos
cluster_setup = setup(knn_anomalies)

In [ ]:
# Code snippet 12
# Building a clustering model using k-Means algorithm
kmeans_model = create_model('kmeans')

Processing:   0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
# Code snippet 13
# Identifying/predicting/assigning the clusters using the kmeans model
kmeans_clusters = assign_model(kmeans_model)

# Displaying Kmeans clusters
kmeans_clusters

,beds,baths,sqft,Age,lot_size,property_type,exterior_walls_Wood Siding,exterior_walls_Brick,exterior_walls_Concrete Block,exterior_walls_Wood,...,married,college_grad,property_tax,insurance,median_school,num_schools,Sales_price,Anomaly,Anomaly_Score,Cluster
0,1.0,1.0,584.0,9.0,0.0,0.0,1.0,0.0,0.0,0.0,...,65.0,84.0,234.0,81.0,9.0,3.0,295850.0,0,1058.478638,Cluster 2
1,1.0,1.0,612.0,57.0,0.0,0.0,0.0,1.0,0.0,0.0,...,73.0,69.0,169.0,51.0,3.0,3.0,216500.0,0,1542.812012,Cluster 2
2,1.0,1.0,615.0,59.0,0.0,0.0,1.0,0.0,0.0,0.0,...,15.0,86.0,216.0,74.0,8.0,3.0,279900.0,0,536.152954,Cluster 2
3,1.0,1.0,618.0,22.0,33541.0,0.0,1.0,0.0,0.0,0.0,...,25.0,91.0,265.0,92.0,9.0,3.0,379900.0,0,8684.916992,Cluster 1
4,1.0,1.0,634.0,30.0,0.0,0.0,0.0,1.0,0.0,0.0,...,20.0,75.0,88.0,30.0,9.0,3.0,340000.0,0,1583.929565,Cluster 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1878,5.0,6.0,6381.0,18.0,224334.0,1.0,0.0,0.0,0.0,0.0,...,76.0,87.0,1250.0,381.0,10.0,3.0,385000.0,1,83879.406250,Cluster 1
1879,5.0,6.0,6501.0,66.0,23086.0,1.0,0.0,1.0,0.0,0.0,...,73.0,61.0,1553.0,473.0,9.0,3.0,690000.0,0,10610.535156,Cluster 0
1880,5.0,6.0,7064.0,27.0,217800.0,1.0,0.0,0.0,0.0,0.0,...,87.0,66.0,942.0,287.0,8.0,1.0,600000.0,1,90006.031250,Cluster 0
1881,5.0,6.0,7500.0,16.0,8886.0,1.0,0.0,0.0,0.0,0.0,...,61.0,51.0,803.0,245.0,5.0,2.0,759900.0,0,7099.341309,Cluster 0
1882,5.0,6.0,7515.0,64.0,10497.0,1.0,0.0,1.0,0.0,0.0,...,80.0,86.0,1459.0,444.0,9.0,3.0,735000.0,0,7063.792969,Cluster 0

In [ ]:
# Code snippet 14
# Exporting the dataset with anomalies and clusters info
kmeans_clusters.to_csv('Zillow data with Anomalies and Clusters.csv')